CREATE TABLE DEPT_T
(
    DEPT_NUM VARCHAR2(15 BYTE) NOT NULL PRIMARY KEY,
    DEPT_NAME VARCHAR2(30 BYTE),
    DEPT_LOCATION VARCHAR2(50 BYTE)
);

CREATE TABLE EMPLOYEE_T
(
    EMP_NUM NUMBER NOT NULL PRIMARY KEY,
    DEPT_NO VARCHAR2(15 BYTE) REFERENCES DEPT_T(DEPT_NUM) ON DELETE SET NULL,
    POSITION CHAR(10 BYTE),
    NAME VARCHAR2(15 BYTE),
    HIRE_DATE DATE,
    SALARY NUMBER
);

CREATE TABLE PROJECT_T
(
    PJT_NUM NUMBER NOT NULL PRIMARY KEY,
    PJT_NAME VARCHAR2(30 BYTE),
    BEGIN_DATE DATE,
    END_DATE DATE
);

CREATE TABLE PROCEEDING_T
(
    PCD_NUM NUMBER NOT NULL PRIMARY KEY,
    EMP_NUM NUMBER REFERENCES EMPLOYEE_T(EMP_NUM) ON DELETE CASCADE,
    PJT_NUM NUMBER REFERENCES PROJECT_T(PJT_NUM) ON DELETE SET NULL,
    PJT_STATE NUMBER NOT NULL
);

DROP TABLE PROCEEDING_T;
DROP TABLE PROJECT_T;
DROP TABLE EMPLOYEE_T;
DROP TABLE DEPT_T;




