CREATE TABLE CAR_T
(
    COMPANY VARCHAR2(1 BYTE) NOT NULL PRIMARY KEY
);

CREATE TABLE HD_T
(
    COMPANY VARCHAR2(1 BYTE) REFERENCES CAR_T(COMPANY),
    PRICE NUMBER NOT NULL PRIMARY KEY
);

CREATE TABLE KIA_T
(
    COMPANY VARCHAR2(1 BYTE) REFERENCES CAR_T(COMPANY),
    PRICE NUMBER NOT NULL PRIMARY KEY
);

CREATE TABLE A_T
(
    PRICE NUMBER REFERENCES HD_T(PRICE)
);

CREATE TABLE B_T
(
    PRICE NUMBER REFERENCES KIA_T(PRICE)
);


DROP TABLE B_T;
DROP TABLE A_T;
DROP TABLE KIA_T;
DROP TABLE HD_T;
DROP TABLE CAR_T;


